# Generated by Django 2.0.5 on 2018-05-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='applied',
            name='post_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='applied',
            name='status',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='post_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='status',
            field=models.TextField(blank=True, default=''),
        ),
    ]
